In [4]:
import pandas as pd;
from matplotlib import pyplot as plt;

In [2]:
import numpy as np;

In [5]:
heart_data = pd.read_csv("087 heart-disease.csv")

In [6]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
x = heart_data.drop("target",axis=1)
y = heart_data["target"]

In [7]:
from sklearn.ensemble import RandomForestClassifier;
from sklearn.model_selection import train_test_split;

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [11]:
clf = RandomForestClassifier(n_estimators=100)

In [13]:
clf.fit(x_train,y_train);

In [15]:
clf.score(x_test,y_test)

0.8032786885245902

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
clf2 = KNeighborsClassifier(n_neighbors=45)

In [37]:
clf2.fit(x_train,y_train);

In [38]:
clf2.score(x_test,y_test)

0.7049180327868853

In [40]:
from sklearn.svm import SVC

In [43]:
clf3 = SVC(kernel = 'linear',C= 3)

In [44]:
clf3.fit(x_train,y_train)

SVC(C=3, kernel='linear')

In [45]:
clf3.score(x_test,y_test)

0.7868852459016393

In [5]:
data2 = pd.read_csv("car-sales-extended.csv")
data2

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [6]:
from sklearn import preprocessing

In [7]:
encoder = preprocessing.LabelEncoder()

In [21]:
data3 = data2.drop("Price",axis=1)

In [28]:
data4 = data2

In [29]:
data4

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [16]:
makemodified = encoder.fit_transform(list(data2["Make"]))
Doors = encoder.fit_transform(list(data2["Doors"]))
colour = encoder.fit_transform(list(data2["Colour"]))

In [32]:
data4["Make"] = encoder.fit_transform(data2["Make"])
data4["Doors"] = encoder.fit_transform(data2["Doors"])
data4["Colour"] = encoder.fit_transform(data2["Colour"])

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categories = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categories)],
                               remainder="passthrough")

transformed_x = pd.DataFrame(transformer.fit_transform(data3))

In [25]:
transformed_x

0    1    2    3    4    5    6    7    8    9   10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [27]:
dummies = pd.get_dummies(data2[["Make","Colour","Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [33]:
data4

Make  Colour  Odometer (KM)  Doors  Price
0       1       4          35431      1  15323
1       0       1         192714      2  19943
2       1       4          84714      1  28343
3       3       4         154365      1  13434
4       2       1         181577      0  14043
..    ...     ...            ...    ...    ...
995     3       0          35820      1  32042
996     2       4         155144      0   5716
997     2       1          66604      1  31570
998     1       4         215883      1   4001
999     3       1         248360      1  12732

[1000 rows x 5 columns]

In [36]:
x = data4.drop("Price",axis=1)
y = data4["Price"]

In [34]:
from sklearn.ensemble import RandomForestRegressor

clf = RandomForestRegressor()

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [40]:
clf.fit(x_train,y_train)

RandomForestRegressor()

In [41]:
clf.score(x_test,y_test)

0.3464614913574551

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
clf2 = LinearRegression()

In [46]:
clf2.fit(x_train,y_train)

LinearRegression()

In [47]:
clf2.score(x_test,y_test)

0.2932196959006187

In [49]:
x_test.head()

Make  Colour  Odometer (KM)  Doors
423     2       0         141109      1
700     1       1         203447      1
703     1       1         224900      1
533     3       2         221725      1
127     0       3          35807      2

In [50]:
y_test.head()

423    23130
700     3509
703     9104
533     6742
127    17596
Name: Price, dtype: int64

In [63]:
clf.predict([[2,0,141109,1],[2,0,141109,1]])   #np.array([2,0,141109,1]) .reshape(1,-1))

array([10348.46, 10348.46])

In [60]:
np.array([2,0,141109,1]).reshape(1,-1)

array([[     2,      0, 141109,      1]])

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
import numpy as np

In [6]:
car_missing = pd.read_csv("car-sales-extended-missing-data.csv")

In [7]:
car_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [9]:
car_missing.dropna(subset = ["Price","Doors"],inplace = True)

In [11]:
car_missing.isna().sum()

Make             46
Colour           43
Odometer (KM)    47
Doors             0
Price             0
dtype: int64

In [2]:
from sklearn.datasets import load_boston;

In [5]:
boston = load_boston()
# boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
b_data = pd.DataFrame(boston["data"],columns=boston["feature_names"])
b_data["target"] = boston["target"]

In [10]:
b_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [19]:
from sklearn.linear_model import Ridge;

x = b_data.drop("target",axis=1)
y = b_data["target"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

model = Ridge()

model.fit(x_train,y_train)

model.score(x_test,y_test)

0.7815515769311133

In [20]:
model.score(x_test,y_test)

0.7815515769311133

In [10]:
from sklearn.ensemble import RandomForestRegressor

clf = RandomForestRegressor(n_estimators=100)

clf.fit(x_train,y_train)

clf.score(x_test,y_test)

0.3865340909090911

In [23]:
from sklearn.linear_model import LinearRegression

clf2 = LinearRegression()

clf2.fit(x_train,y_train)

clf2.score(x_test,y_test)

0.7844274324031925

In [38]:
clf.predict(np.array(x_test.loc[194]).reshape(1, -1))

array([29.116])

In [36]:
y_test

194    29.1
9      18.9
358    22.7
159    23.3
416     7.5
       ... 
130    19.2
459    20.0
40     34.9
493    21.8
212    22.4
Name: target, Length: 102, dtype: float64

In [40]:
clf.predict(np.array(x_test.loc[194]).reshape(1, -1))

array([29.116])

In [41]:
from sklearn.model_selection import cross_val_score

In [44]:
np.mean(cross_val_score(clf,x,y,cv=5))

0.622572006789044

In [4]:
from sklearn.metrics import recall_score,accuracy_score,precision_score,f1_score

In [13]:
def analyse(y_true,y_preds):
    accuracy = accuracy_score(y_true,y_preds)
    recall = recall_score(y_true,y_preds)
    precision = precision_score(y_true,y_preds)
    f1 = f1_score(y_true,y_preds)
    
    metric_dict = {
        "accuracy":round(accuracy),
        "recall":round(recall),
        "precision":round(precision),
        "f1":round(f1,2)
    }
    
    print(f'accuracy:{accuracy:.2f}')
    print(f'recall:{recall:.2f}')
    print(f'precision:{precision:.2f}')
    print(f'f1:{f1:.2f}')
    
    return metric_dict

In [2]:
from sklearn.ensemble import RandomForestClassifier;

In [7]:
heart_data = heart_data.sample(frac=1)

In [8]:
np.random.seed(42)

x = heart_data.drop("target",axis=1)
y = heart_data["target"]

train_length = round(0.7*len(heart_data))
valid_len = round(train_length+0.15*len(heart_data))
x_train,y_train = x[:train_length], y[:train_length]
x_valid,y_valid = x[train_length:valid_len],y[train_length:valid_len]
x_test ,y_test = x[valid_len:],y[valid_len:]

len(x_valid),len(x_train),len(x_test)

(45, 212, 46)

In [9]:
clf = RandomForestClassifier()

clf.fit(x_train,y_train)

RandomForestClassifier()

In [14]:
y_preds = clf.predict(x_valid)

baseline_metrics = analyse(y_valid,y_preds)
baseline_metrics

accuracy:0.84
recall:0.90
precision:0.87
f1:0.88


{'accuracy': 1, 'recall': 1, 'precision': 1, 'f1': 0.88}

In [15]:
from sklearn.model_selection import RandomizedSearchCV

grid = {
    "n_estimators":[10,100,200,500,1000,1200],
    "max_depth":[None,5,10,20,30],
    "max_features":["auto","sqrt"],
    "min_samples_split":[2,4,6],
    "min_samples_leaf":[1,2,4]
}